POST https://api.telegram.org/bot{token}/setWebhook?url=https://botler.kvn.pt/bot?token={token}

###

POST http://localhost:8000/bot?token={token}
Content-Type: application/json

{
  "message": {
    "text": "/mc"
  }
}

###

POST https://botler.kvn.pt/bot?token={token}
Content-Type: application/json

{
  "message": {
    "text": "/mc"
  }
}
