POST https://api.telegram.org/bot{token}/setWebhook?url=https://botler.g.kvn.pt/bot?token={token}

###

POST https://botler.g.kvn.pt/bot
Content-Type: application/json

{
  "message": {
    "text": "/ip"
  }
}

###

POST https://botler.g.kvn.pt/bot
Content-Type: application/json

{
  "message": {
    "text": "/stock ASII=10 BBCA=3"
  }
}

###

POST https://botler.g.kvn.pt/send
Content-Type: application/json

{
  "chat_id": "{chat_id}",
  "text": "Hello world"
}
